export default [
    {
        identifier: "bronzeHatchet",
        name: "Bronze hatchet",
        value: 84,
        bonus: 5,
        level: 1,
    },
    {
        identifier: "ironHatchet",
        name: "Iron hatchet",
        value: 126,
        bonus: 7,
        level: 1,
    },
    {
        identifier: "steelHatchet",
        name: "Steel hatchet",
        value: 168,
        bonus: 10,
        level: 6,
    },
    {
        identifier: "blackHatchet",
        name: "Black hatchet",
        value: 384,
        bonus: 12,
        level: 6,
    },
    {
        identifier: "mythrilHatchet",
        name: "Mythril hatchet",
        value: 251,
        bonus: 15,
        level: 21,
    },
    {
        identifier: "adamantHatchet",
        name: "Adamant hatchet",
        value: 334,
        bonus: 20,
        level: 31,
    },
    {
        identifier: "runeHatchet",
        name: "Rune hatchet",
        value: 834,
        bonus: 25,
        level: 41,
    },
    {
        identifier: "dragonHatchet",
        name: "Dragon hatchet",
        value: 55000,
        bonus: 30,
        level: 61,
    },
    {
        identifier: "crystalHatchet",
        name: "Crystal hatchet",
        value: 0,
        bonus: 40,
        level: 71,
    },
];
