export default [
    {
        identifier: "acadiaLogs",
        name: "Acadia logs",
        value: 85,
        exp: 92,
        level: 47,
    },
    {
        identifier: "acheyLogs",
        name: "Achey tree logs",
        value: 4,
        exp: 25,
        level: 1,
    },
    {
        identifier: "arcticPineLogs",
        name: "Arctic pine logs",
        value: 35,
        exp: 140.2,
        level: 54,
    },
    {
        identifier: "blisterwoodLogs",
        name: "Blisterwood logs",
        value: 1,
        exp: 200,
        level: 76,
    },
    {
        identifier: "elderLogs",
        name: "Elder logs",
        value: 480,
        exp: 325,
        level: 90,
    },
    {
        identifier: "eucalyptusLogs",
        name: "Eucalyptus logs",
        value: 126,
        exp: 165,
        level: 58,
    },
    {
        identifier: "logs",
        name: "Logs",
        value: 4,
        exp: 25,
        level: 1,
    },
    {
        identifier: "mahoganyLogs",
        name: "Mahogany logs",
        value: 500,
        exp: 125,
        level: 50,
    },
    {
        identifier: "magicLogs",
        name: "Magic logs",
        value: 320,
        exp: 250,
        level: 75,
    },
    {
        identifier: "mapleLogs",
        name: "Maple logs",
        value: 80,
        exp: 100,
        level: 45,
    },
    {
        identifier: "oakLogs",
        name: "Oak logs",
        value: 20,
        exp: 37.5,
        level: 15,
    },
    {
        identifier: "teakLogs",
        name: "Teak logs",
        value: 30,
        exp: 85,
        level: 35,
    },
    {
        identifier: "willowLogs",
        name: "Willow logs",
        value: 40,
        exp: 67.5,
        level: 30,
    },
    {
        identifier: "yewLogs",
        name: "Yew logs",
        value: 160,
        exp: 175,
        level: 60,
    },
];
